title: Gaurja Newatia
logo: photo_d.jpg
description: >
  <br><br>
  <a href="https://www.linkedin.com/in/gnewatia/">View my LinkedIn Profile</a>
  <br>
  <a href=Gaurja_Resume.pdf" download>Download my CV</a>
show_downloads: true
theme: jekyll-theme-minimal

